/* Deep-space catalogs and explicitly labeled reconstructions, independent of Horizons. */
(() => {
'use strict';
const $=id=>document.getElementById(id),T=window.THREE,M=window.SpaceModel;
const compact=matchMedia('(max-width:900px)'),phone=compact.matches||matchMedia('(pointer:coarse)').matches,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
let layer='milky',catalog=null,nearby=null,selected=null,systemHost=null,returnFocus=null;
function drawer(open){document.body.classList.toggle('info-open',open);$('open-info').setAttribute('aria-expanded',String(open));$('space-info').inert=compact.matches&&!open;if(open&&compact.matches){returnFocus=document.activeElement;$('close-info').focus();}else if(compact.matches&&returnFocus){(returnFocus.isConnected?returnFocus:$('open-info')).focus();returnFocus=null;}}
$('open-info').onclick=()=>drawer(!document.body.classList.contains('info-open'));$('close-info').onclick=()=>drawer(false);
compact.addEventListener('change',()=>{const wasFocused=$('space-info').contains(document.activeElement)||document.activeElement===$('open-info');drawer(false);if(wasFocused)(compact.matches?$('open-info'):$('target')).focus();returnFocus=null;});drawer(false);
window.addEventListener('keydown',e=>{if(e.key==='Escape')drawer(false);});
function clock(){const iso=new Date().toISOString();$('utc-clock').textContent=iso.slice(0,10)+' '+iso.slice(11,19)+' UTC';$('utc-clock').dateTime=iso;}
clock();setInterval(()=>{if(!document.hidden)clock();},1000);
if(!T||!M){$('loading').textContent='The 3D renderer could not load. Reload to try again.';return;}
let renderer;try{renderer=new T.WebGLRenderer({antialias:!phone,alpha:true,powerPreference:phone?'default':'high-performance'});}catch(_){$('loading').textContent='WebGL is unavailable on this device.';return;}
renderer.setPixelRatio(Math.min(devicePixelRatio,phone?1.25:2));renderer.setClearColor(0,0);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;
renderer.domElement.setAttribute('role','img');renderer.domElement.setAttribute('aria-label','Interactive catalog space map. Use the four scale buttons and target selector to explore. Galaxy and black-hole appearances are reconstructions.');$('space-scene').append(renderer.domElement);
let homeDistance=49;const homeFocus=new T.Vector3();
const scene=new T.Scene(),camera=new T.PerspectiveCamera(42,1,.02,10000),world=new T.Group();scene.add(world);
scene.add(new T.AmbientLight(0xa5bed4,1.2));const light=new T.PointLight(0xffd4a0,80,100,2);scene.add(light);
let theta=.32,phi=.77,distance=49,targetDistance=49,focus=new T.Vector3(),targetFocus=new T.Vector3(),width=1,height=1,labels=[],pickable=[],animatedMaterial=null;
let seed=34089;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
const glowCanvas=document.createElement('canvas');glowCanvas.width=glowCanvas.height=128;const ctx=glowCanvas.getContext('2d'),gradient=ctx.createRadialGradient(64,64,0,64,64,64);gradient.addColorStop(0,'rgba(255,255,255,1)');gradient.addColorStop(.12,'rgba(255,255,255,.9)');gradient.addColorStop(.4,'rgba(255,255,255,.14)');gradient.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=gradient;ctx.fillRect(0,0,128,128);const glowTexture=new T.CanvasTexture(glowCanvas);
function clear(){world.traverse(o=>{o.geometry?.dispose();if(o.material){for(const mat of Array.isArray(o.material)?o.material:[o.material])mat.dispose();}});world.clear();$('space-labels').replaceChildren();labels=[];pickable=[];animatedMaterial=null;systemHost=null;}
function mark(name,point,action,priority=0){const wrap=document.createElement('div');wrap.className='label';const button=document.createElement('button');button.textContent=name;button.onclick=action;wrap.append(button);$('space-labels').append(wrap);const record={el:wrap,point:new T.Vector3(...point),priority};labels.push(record);return record;}
function star(point,color=0xffdfad,size=.25){const s=new T.Sprite(new T.SpriteMaterial({map:glowTexture,color,transparent:true,depthWrite:false,blending:T.AdditiveBlending}));s.position.set(...point);s.scale.setScalar(size);world.add(s);return s;}
function galaxy(radius=15.3,count=24000,shape='spiral',barred=false){
 const pos=[],colors=[];
 for(let i=0;i<count;i++){
  const bulge=i<count*.19,r=bulge?Math.pow(random(),1.7)*radius*.2:Math.sqrt(random())*radius;
  const arm=i%4,angle=shape==='spiral'&&!bulge?arm*Math.PI/2+Math.log(Math.max(r/radius,.015))*2.8+(random()-.5)*.6:random()*Math.PI*2;
  const flatten=shape==='irregular'?.35:1,thickness=bulge?radius*.06:radius*.018;
  if(shape==='elliptical'){const z=random()*2-1,rr=radius*Math.pow(random(),.8),rrxy=Math.sqrt(1-z*z);pos.push(Math.cos(angle)*rrxy*rr,z*rr*.65,Math.sin(angle)*rrxy*rr*.85);}else pos.push(Math.cos(angle)*r*(barred&&bulge?1.45:1),(random()-.5)*thickness,Math.sin(angle)*r*flatten*(barred&&bulge?.45:1));
  const c=new T.Color(bulge||shape==='elliptical'?0xffd4a0:random()>.35?0x9bbcef:0xeee3d3);c.multiplyScalar(.5+random()*.6);colors.push(c.r,c.g,c.b);
 }
 const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(pos,3));g.setAttribute('color',new T.Float32BufferAttribute(colors,3));
 const material=new T.PointsMaterial({size:radius/(phone?95:130),map:glowTexture,vertexColors:true,transparent:true,opacity:.82,depthWrite:false,blending:T.AdditiveBlending});const points=new T.Points(g,material);world.add(points);return points;
}
function line(points,color=0x325463){const g=new T.BufferGeometry().setFromPoints(points.map(p=>new T.Vector3(...p)));const o=new T.Line(g,new T.LineBasicMaterial({color,transparent:true,opacity:.55,depthWrite:false}));world.add(o);return o;}
function buildMilky(){galaxy(catalog.milkyWay.diameterLy/(M.PC_TO_LY*2000),phone?12000:32000,'spiral',true);const sunX=catalog.milkyWay.solarRadiusLy/(M.PC_TO_LY*1000);star([sunX,0,0],0x79f4e5,.65);star([0,0,0],0xffbd82,.55);mark('Our Solar System ↗',[sunX,.15,0],()=>{location.href='/';},10);mark('Sagittarius A* ↗',[0,.15,0],()=>{setLayer('blackholes');choose('sgr-a');},9);line([[0,0,0],[sunX,0,0]],0x42827c);targetFocus.set(0,0,0);targetDistance=phone?64:48;}
function buildNearby(){const positions=[],colors=[];for(const h of nearby.hosts){const p=M.position(h.raDeg,h.decDeg,h.distancePc).map(v=>v/3);positions.push(...p);const c=new T.Color(M.starColor(h.temperatureK));colors.push(c.r,c.g,c.b);pickable.push({object:h,point:new T.Vector3(...p)});}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(positions,3));g.setAttribute('color',new T.Float32BufferAttribute(colors,3));world.add(new T.Points(g,new T.PointsMaterial({size:phone?.17:.12,map:glowTexture,vertexColors:true,transparent:true,depthWrite:false,blending:T.AdditiveBlending})));star([0,0,0],0x79f4e5,.45);mark('Sun · our system',[0,0,0],()=>{location.href='/';},10);nearby.hosts.slice(0,9).forEach((h,i)=>{const p=M.position(h.raDeg,h.decDeg,h.distancePc).map(v=>v/3);star(p,M.starColor(h.temperatureK),.3);mark(h.name,p,()=>choose(h.id),9-i);});targetFocus.set(0,0,0);targetDistance=phone?48:36;}
function buildGalaxies(){for(const o of catalog.objects.filter(o=>o.type==='galaxy')){const p=M.compress(M.position(o.raDeg,o.decDeg,o.distancePc),1e6);const glyph=galaxy(o.morphology==='elliptical'?.7:.9,phone?650:1500,o.morphology);glyph.position.set(...p);glyph.rotation.set(.25,0,.2);mark(o.name,p,()=>choose(o.id),o.id==='m31'?10:2);pickable.push({object:o,point:new T.Vector3(...p)});}star([0,0,0],0x79f4e5,.5);mark('Milky Way ↗',[0,0,0],()=>setLayer('milky'),9);targetFocus.set(0,0,0);targetDistance=phone?75:58;}
function buildBlackhole(){
 const sphere=new T.Mesh(new T.SphereGeometry(2,phone?48:80,32),new T.MeshBasicMaterial({color:0x000000}));world.add(sphere);
 const ring=new T.RingGeometry(3.1,10,phone?128:192,3),p=ring.attributes.position,uv=ring.attributes.uv;
 for(let i=0;i<p.count;i++)uv.setXY(i,(Math.atan2(p.getY(i),p.getX(i))+Math.PI)/(2*Math.PI),(Math.hypot(p.getX(i),p.getY(i))-3.1)/6.9);
 ring.rotateX(-Math.PI/2);
 animatedMaterial=new T.ShaderMaterial({side:T.DoubleSide,transparent:true,depthWrite:false,uniforms:{time:{value:0}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec2 vUv;uniform float time;
 void main(){float r=vUv.y;float a=vUv.x*6.28318;float streams=.72+.2*sin(a*13.+r*39.-time)+.08*sin(a*31.-r*77.);float edge=smoothstep(0.,.06,r)*(1.-smoothstep(.65,1.,r));float heat=pow(1.-r,2.);vec3 c=mix(vec3(.42,.075,.012),vec3(1.,.72,.32),heat);c=mix(c,vec3(1.,.94,.78),pow(1.-r,9.));float beam=.45+.55*(.5+.5*cos(a));gl_FragColor=vec4(c*streams*(.7+beam),edge*.85);
 #include <tonemapping_fragment>
 #include <colorspace_fragment>
 }`});world.add(new T.Mesh(ring,animatedMaterial));
 const photon=new T.Mesh(new T.TorusGeometry(2.7,.055,8,phone?96:160),new T.MeshBasicMaterial({color:0xffbc6e,transparent:true,opacity:.7}));photon.userData.faceCamera=true;world.add(photon);star([0,0,0],0xf29a55,6.5);targetFocus.set(0,0,0);targetDistance=phone?42:33;phi=1.16;
}
function buildSystem(host){clear();systemHost=host;star([0,0,0],M.starColor(host.temperatureK),2.8);const sphere=new T.SphereGeometry(1,phone?32:48,24);for(const item of M.systemLayout(host.planets)){if(item.radius===null)continue;const p=item.planet,r=item.radius;line(Array.from({length:129},(_,i)=>[Math.cos(i*Math.PI/64)*r,0,Math.sin(i*Math.PI/64)*r]));const body=new T.Mesh(sphere.clone(),new T.MeshStandardMaterial({color:p.pl_rade>3?0x96a9bf:0xb5a394,roughness:1}));body.position.set(Math.cos(item.angle)*r,0,Math.sin(item.angle)*r);body.scale.setScalar(p.pl_rade>0?Math.min(.65,.12+.14*Math.sqrt(p.pl_rade)):.22);world.add(body);mark(p.pl_name,body.position.toArray(),()=>showPlanet(p,host),4);}
 sphere.dispose();$('view-title').textContent=host.name;$('view-kind').textContent='CONFIRMED EXOPLANET SYSTEM';$('view-note').textContent='Orbit size diagram · phase, orientation and surface appearance unavailable';$('display-scale').textContent='Compressed semimajor-axis guides · Planet phases are illustrative';targetFocus.set(0,0,0);targetDistance=Math.max(20,...M.systemLayout(host.planets).map(i=>(i.radius||0)*3.5))*(phone?1.3:1);distance=targetDistance;focus.copy(targetFocus);homeDistance=targetDistance;homeFocus.copy(targetFocus);if(compact.matches)drawer(false);}
function fact(label,value){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;$('facts').append(dt,dd);}
const number=(n,unit='',digits=2)=>Number.isFinite(n)?n.toLocaleString('en-GB',{maximumFractionDigits:digits})+(unit?' '+unit:''):'Unavailable';
function baseInfo(o){$('facts').replaceChildren();$('actions').replaceChildren();$('planet-list').replaceChildren();$('planet-section').hidden=true;$('observation').hidden=true;$('object-name').textContent=o.name;$('object-description').textContent=o.note||o.positionNote||'';$('source-link').href=o.source||'https://exoplanetarchive.ipac.caltech.edu/';if(o.distancePc){const ly=o.distancePc*M.PC_TO_LY;fact('DISTANCE FROM OUR SUN',(o.distanceApproximate?'≈ ':'')+number(ly,'light-years'));fact('APPROXIMATE LIGHT-TRAVEL TIME',number(ly,'years'));}if(Number.isFinite(o.raDeg)){fact('CATALOG RA / DEC',number(o.raDeg,'°',4)+' / '+number(o.decDeg,'°',4));}}
function action(text,fn){const b=document.createElement('button');b.textContent=text;b.onclick=fn;$('actions').append(b);}
function showPlanet(p,host){baseInfo({...host,name:p.pl_name});$('object-type').textContent='CONFIRMED EXOPLANET · INFERRED APPEARANCE';$('object-description').textContent='Measured archive parameters. Displayed color, orientation and orbital phase are illustrative. Semimajor-axis guides are circles, not reconstructed instantaneous orbits.';fact('ORBITAL PERIOD',number(p.pl_orbper,'days'));fact('SEMIMAJOR AXIS',number(p.pl_orbsmax,'AU',4));fact('RADIUS',number(p.pl_rade,'Earth radii'));fact('MASS / MASS ESTIMATE',number(p.pl_bmasse,'Earth masses'));fact('DISCOVERY',p.discoverymethod+' · '+p.disc_year);action('Back to '+host.name,()=>{showInfo(host);});}
function showInfo(o){selected=o;baseInfo(o);if(o.id==='milky'){$('object-type').textContent='STRUCTURAL RECONSTRUCTION';fact('ADOPTED DISK DIAMETER','≈ 100,000 light-years');fact('SUN TO GALACTIC CENTER','≈ 26,000 light-years');$('object-description').textContent=catalog.milkyWay.note;action('Explore Sagittarius A*',()=>setLayer('blackholes'));action('Explore nearby planetary systems',()=>setLayer('nearby'));const a=document.createElement('a');a.href='/';a.textContent='Return to the live Solar System ↗';$('actions').append(a);}else if(o.type==='star'){$('object-type').textContent='CATALOG POSITION · CONFIRMED PLANETS';fact('CONFIRMED PLANETS',o.planets.length);fact('STELLAR TEMPERATURE',number(o.temperatureK,'K',0));$('planet-section').hidden=false;for(const p of o.planets){const b=document.createElement('button');b.textContent=p.pl_name;const s=document.createElement('small');s.textContent='Period '+number(p.pl_orbper,'days')+' · Radius '+number(p.pl_rade,'R⊕');b.append(s);b.onclick=()=>{buildSystem(o);showPlanet(p,o);};$('planet-list').append(b);}action('Explore planet orbit-size diagram',()=>{buildSystem(o);showInfo(o);});if(systemHost)action('Back to nearby-star map',()=>setLayer('nearby'));}
 else if(o.type==='blackhole'){$('object-type').textContent='OBSERVED OBJECT · VISUAL RECONSTRUCTION';fact('ESTIMATED MASS',number(o.massSolar,'solar masses',0));fact('NONROTATING HORIZON REFERENCE',number(M.schwarzschildKm(o.massSolar)/M.AU_KM,'AU',4));$('object-description').textContent=o.note+' The 3D disk and lens ring are illustrative, not a relativistic ray trace. Horizon reference assumes zero spin.';action('Locate its host galaxy',()=>{if(o.id==='sgr-a')setLayer('milky');else{setLayer('galaxies');choose('m87');}});action('Animate illustrative gas / stop',()=>{if(animatedMaterial)animatedMaterial.userData.animate=!animatedMaterial.userData.animate;});}
 else $('object-type').textContent='CATALOG POSITION · RECONSTRUCTED SHAPE';
 if(o.image){$('observation').hidden=false;$('observation-image').hidden=false;$('observation-image').onerror=()=>{if(selected?.id!==o.id)return;$('observation-image').hidden=true;$('observation-caption').textContent+=' · Image unavailable; use the observation link.';};$('observation-image').src=o.image;$('observation-image').alt='Recorded observation of '+o.name;$('observation-link').href=o.imageSource;$('observation-caption').textContent='RECORDED OBSERVATION · '+o.imageDate+' · '+o.imageCredit+' · '+o.imageLicense;}
 $('announcement').textContent='Exploring '+o.name;
}
function targets(){return layer==='milky'?[{id:'milky',name:'Milky Way',source:catalog.milkyWay.source}]:layer==='nearby'?nearby.hosts:catalog.objects.filter(o=>o.type===(layer==='blackholes'?'blackhole':'galaxy'));}
function choose(id){if(!catalog||!nearby)return;if(layer==='nearby'&&systemHost)setLayer('nearby');const o=targets().find(o=>o.id===id);if(!o)return;$('target').value=o.id;if(layer==='blackholes'){clear();buildBlackhole();distance=targetDistance;focus.copy(targetFocus);}else if(layer!=='milky'){const unit=layer==='nearby'?3:1;const p=layer==='nearby'?M.position(o.raDeg,o.decDeg,o.distancePc).map(v=>v/unit):M.compress(M.position(o.raDeg,o.decDeg,o.distancePc),1e6);targetFocus.set(...p);targetDistance=layer==='nearby'?9:8;for(const l of labels.filter(l=>l.selected))l.el.remove();labels=labels.filter(l=>!l.selected);mark(o.name,p,()=>{if(compact.matches)drawer(true);},20).selected=true;}homeDistance=targetDistance;homeFocus.copy(targetFocus);showInfo(o);if(layer==='blackholes')$('view-title').textContent=o.name;}
function setLayer(next){if(!catalog||!nearby)return;layer=next;clear();theta=.32;phi=.77;for(const b of document.querySelectorAll('[data-layer]'))b.setAttribute('aria-pressed',String(b.dataset.layer===next));$('target').replaceChildren();for(const o of targets()){const opt=document.createElement('option');opt.value=o.id;opt.textContent=o.name;$('target').append(opt);}
 const titles={milky:['OUR GALAXY','Milky Way','Reconstructed structure · Explore our Solar System and galactic center','1 unit ≈ 1,000 parsecs · Model stars'],nearby:['SOLAR NEIGHBORHOOD','Nearby systems','Confirmed exoplanet hosts within 30 parsecs · Catalog positions','ICRS frame · 1 unit = 3 parsecs · Star sizes enlarged'],galaxies:['BEYOND THE MILKY WAY','Galaxies','Sourced catalog locations · Reconstructed galaxy shapes','Radial distance compressed · Galaxy markers enlarged'],blackholes:['EXTREME GRAVITY','Sagittarius A*','Observed black holes · Scientific illustration','Horizon-reference units · Appearance is illustrative']};const t=titles[next];$('view-kind').textContent=t[0];$('view-title').textContent=t[1];$('view-note').textContent=t[2];$('display-scale').textContent=t[3];
 if(next==='milky')buildMilky();else if(next==='nearby')buildNearby();else if(next==='galaxies')buildGalaxies();else buildBlackhole();distance=targetDistance;focus.copy(targetFocus);homeDistance=targetDistance;homeFocus.copy(targetFocus);$('search').value='';$('search-results').replaceChildren();showInfo(targets()[0]);$('target').value=targets()[0].id;if(compact.matches)drawer(false);}
for(const b of document.querySelectorAll('[data-layer]'))b.onclick=()=>setLayer(b.dataset.layer);$('target').onchange=e=>choose(e.target.value);
$('search').oninput=()=>{if(!catalog||!nearby)return;const q=$('search').value.trim().toLowerCase();$('search-results').replaceChildren();if(q.length<2)return;const matches=[...nearby.hosts,...catalog.objects].filter(o=>o.name.toLowerCase().includes(q)||(o.planets||[]).some(p=>p.pl_name.toLowerCase().includes(q))).slice(0,8);for(const o of matches){const b=document.createElement('button');b.textContent=o.name;b.onclick=()=>{setLayer(o.type==='star'?'nearby':o.type==='blackhole'?'blackholes':'galaxies');choose(o.id);};$('search-results').append(b);}if(!matches.length)$('search-results').textContent='No matching object in this catalog.';};
$('top').onclick=()=>phi=.015;$('fit').onclick=()=>{targetDistance=homeDistance;targetFocus.copy(homeFocus);};$('zoom-in').onclick=()=>targetDistance=Math.max(3,targetDistance*.78);$('zoom-out').onclick=()=>targetDistance=Math.min(200,targetDistance*1.28);
const pointers=new Map();let pinch=0,dragged=false;
const viewport=$('space-scene');viewport.addEventListener('pointerdown',e=>{viewport.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});dragged=false;});viewport.addEventListener('pointermove',e=>{const old=pointers.get(e.pointerId);if(!old)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const [a,b]=[...pointers.values()],d=Math.hypot(a.x-b.x,a.y-b.y);if(pinch)targetDistance=T.MathUtils.clamp(targetDistance*pinch/d,3,200);pinch=d;dragged=true;return;}const dx=e.clientX-old.x,dy=e.clientY-old.y;if(Math.abs(dx)+Math.abs(dy)>1)dragged=true;theta-=dx*.005;phi=T.MathUtils.clamp(phi+dy*.005,.015,Math.PI-.015);});
function end(e){pointers.delete(e.pointerId);pinch=0;if(dragged||e.type==='pointercancel')return;const rect=viewport.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;let best=24,hit=null;for(const p of pickable){const v=p.point.clone().project(camera),gap=Math.hypot((v.x+1)*width/2-x,(1-v.y)*height/2-y);if(v.z<1&&v.z> -1&&gap<best){best=gap;hit=p.object;}}if(hit){choose(hit.id);if(compact.matches)drawer(true);}}viewport.addEventListener('pointerup',end);viewport.addEventListener('pointercancel',end);viewport.addEventListener('wheel',e=>{e.preventDefault();targetDistance=T.MathUtils.clamp(targetDistance*Math.exp(e.deltaY*.001),3,200);},{passive:false});
new ResizeObserver(()=>{width=Math.max(1,viewport.clientWidth);height=Math.max(1,viewport.clientHeight);renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();}).observe(viewport);
function positionLabels(){const used=[];for(const l of [...labels].sort((a,b)=>b.priority-a.priority)){l.el.hidden=true;const p=l.point.clone().project(camera),x=(p.x+1)*width/2,y=(1-p.y)*height/2;if(p.z< -1||p.z>1||x<0||x>width||y<0||y>height)continue;const w=Math.min(190,Math.max(70,l.el.textContent.length*(phone?6:7)+20)),h=phone?44:32,top=height<300?55:145,bottom=height<300?50:65;const options=[[x+10,y-h/2],[x-w-10,y-h/2],[x-w/2,y-h-12],[x-w/2,y+12]];for(const [bx,by] of options){const box={x:bx,y:by,w,h};if(bx<8||bx+w>width-8||by<top||by+h>height-bottom||used.some(o=>box.x<o.x+o.w+4&&box.x+box.w+4>o.x&&box.y<o.y+o.h+4&&box.y+box.h+4>o.y))continue;l.el.hidden=false;l.el.style.transform=`translate(${box.x}px,${box.y}px)`;used.push(box);break;}}}
let last=performance.now(),lastDraw=-Infinity,lastLabels=-Infinity;
document.addEventListener('visibilitychange',()=>{last=performance.now();lastDraw=-Infinity;pointers.clear();if(!document.hidden)clock();});
function frame(now){requestAnimationFrame(frame);if(document.hidden){last=now;return;}if(now-lastDraw<1000/(phone?30:60)-.5)return;const dt=Math.min(.1,Math.max(0,(now-last)/1000));last=now;lastDraw=now;const ease=reduced?1:1-Math.exp(-dt*6);distance+=(targetDistance-distance)*ease;focus.lerp(targetFocus,ease);camera.position.set(focus.x+distance*Math.sin(phi)*Math.sin(theta),focus.y+distance*Math.cos(phi),focus.z+distance*Math.sin(phi)*Math.cos(theta));camera.lookAt(focus);camera.updateMatrixWorld();light.position.copy(camera.position);for(const o of world.children)if(o.userData.faceCamera)o.quaternion.copy(camera.quaternion);if(animatedMaterial?.userData.animate&&!reduced)animatedMaterial.uniforms.time.value+=dt;renderer.render(scene,camera);if(now-lastLabels>160){positionLabels();lastLabels=now;}}
requestAnimationFrame(frame);
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();$('loading').hidden=false;$('loading').textContent='Graphics context lost. Reload to restore the observatory.';});
(async()=>{try{const responses=await Promise.all([fetch('/assets/space/catalog.json'),fetch('/assets/space/nearby.json')]);if(responses.some(r=>!r.ok))throw new Error('Catalog request failed');[catalog,nearby]=await Promise.all(responses.map(r=>r.json()));if(!catalog.objects?.length||!nearby.hosts?.length)throw new Error('Empty catalog');$('catalog-state').textContent=`${nearby.hosts.length} catalog hosts · ${nearby.hosts.reduce((sum,h)=>sum+h.planets.length,0)} confirmed planets`;$('catalog-date').textContent='NASA catalog retrieved '+nearby.retrievedUTC+' · Curated object coordinates retrieved '+catalog.retrievedUTC+'. This is a dated catalog snapshot; not a completeness claim.';setLayer('milky');const requested=new URLSearchParams(location.search).get('layer');if(['nearby','galaxies','blackholes'].includes(requested))setLayer(requested);$('loading').hidden=true;}catch(error){$('loading').textContent='The space catalog could not load. Reload to retry. No invented catalog positions are substituted.';console.error(error);}})();
})();
