const {test}=require('node:test');const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const ROOT=path.resolve(__dirname,'..'),THREE=require(path.join(ROOT,'assets/three.min.js')),M=require(path.join(ROOT,'space-model.js'));
const catalog=JSON.parse(fs.readFileSync(path.join(ROOT,'assets/space/catalog.json'))),nearby=JSON.parse(fs.readFileSync(path.join(ROOT,'assets/space/nearby.json'))),html=fs.readFileSync(path.join(ROOT,'space.html'),'utf8');
const flush=()=>new Promise(resolve=>setImmediate(resolve));
class Target{constructor(){this.events=new Map();}addEventListener(k,f){if(!this.events.has(k))this.events.set(k,[]);this.events.get(k).push(f);}dispatch(k,e={}){e.target??=this;e.preventDefault??=()=>{};for(const f of this.events.get(k)||[])f(e);this['on'+k]?.(e);}}
async function boot({mobile=false,reduced=false,offline=false,search=''}={}){
 const document=new Target();class Element extends Target{constructor(tag='DIV'){super();this.tagName=tag;this.children=[];this.style={};this.dataset={};this.value='';this.hidden=false;this.isConnected=true;this.clientWidth=mobile?390:1200;this.clientHeight=mobile?600:700;this._text='';const s=new Set();this.classList={contains:k=>s.has(k),toggle(k,v){const on=v??!s.has(k);on?s.add(k):s.delete(k);return on;}};}set textContent(x){this._text=String(x);this.children=[];}get textContent(){return this._text+this.children.map(x=>x.textContent).join('');}append(...x){this.children.push(...x);}replaceChildren(...x){this._text='';this.children=x;}remove(){this.isConnected=false;}setAttribute(k,v){this[k]=v;}focus(){document.activeElement=this;}contains(e){return this===e||this.children.some(x=>x.contains(e));}setPointerCapture(){}getBoundingClientRect(){return {left:0,top:0};}getContext(){return {fillRect(){},createRadialGradient(){return {addColorStop(){}};}};}}
 const elements=new Map([...html.matchAll(/id="([^"]+)"/g)].map(x=>[x[1],new Element()]));const buttons=['milky','nearby','galaxies','blackholes'].map(k=>{const b=new Element('BUTTON');b.dataset.layer=k;return b;});
 Object.assign(document,{body:new Element(),hidden:false,getElementById:k=>elements.get(k),createElement:tag=>new Element(tag),querySelectorAll:()=>buttons});
 let clock=Date.parse('2026-10-08T12:00:00Z'),now=0,renderer;const frames=[],intervals=[],errors=[];class FixedDate extends Date{constructor(...args){super(...(args.length?args:[clock]));}static now(){return clock;}}
 const media=new Target();media.matches=mobile;const win=new Target();Object.assign(win,{THREE:{...THREE,WebGLRenderer:class{constructor(options){this.options=options;this.domElement=new Element('CANVAS');renderer=this;this.count=0;}setPixelRatio(n){this.pixelRatio=n;}setClearColor(){}setSize(){}render(scene,camera){scene.updateMatrixWorld();this.scene=scene;this.camera=camera;this.count++;}}},SpaceModel:M});
 const context={window:win,document,console:{error:e=>errors.push(String(e))},location:{search,href:''},devicePixelRatio:3,matchMedia:q=>q.includes('reduced-motion')?{matches:reduced}:q.includes('max-width')?media:{matches:mobile},ResizeObserver:class{constructor(fn){this.fn=fn;}observe(){this.fn();}},fetch:async url=>({ok:!offline,json:async()=>structuredClone(url.includes('nearby')?nearby:catalog)}),Date:FixedDate,performance:{now:()=>now},setInterval:f=>intervals.push(f),requestAnimationFrame:f=>frames.push(f),URLSearchParams};
 vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(ROOT,'space.js'),'utf8'),context);for(let i=0;i<5;i++)await flush();
 const frame=(dt=1/30)=>{now+=dt*1000;clock+=dt*1000;frames.shift()(now);};frame();
 return {document,elements,buttons,renderer,errors,media,intervals,frame,advance:n=>clock+=n*1000,world:()=>renderer.scene.children.find(o=>o.isGroup),layer(k){buttons.find(b=>b.dataset.layer===k).onclick();frame(.04);},choose(id){elements.get('target').onchange({target:{value:id}});frame(.1);},facts:()=>elements.get('facts').textContent};
}

test('ICRS coordinates preserve catalog distances and handedness, including polar and invalid cases',()=>{assert.deepEqual(M.position(0,0,5),[5,0,-0]);assert(Math.abs(M.position(90,0,5)[2]+5)<1e-12);assert(Math.abs(M.position(45,90,5)[1]-5)<1e-12);assert.equal(M.position(0,91,1),null);assert.equal(M.position(0,0,-1),null);for(const h of nearby.hosts){const p=M.position(h.raDeg,h.decDeg,h.distancePc);assert(Math.abs(Math.hypot(...p)-h.distancePc)<1e-10);}});
test('catalog snapshots have source provenance, valid known objects and explicit unavailable parameters',()=>{assert(nearby.hosts.length>=300);const planets=nearby.hosts.flatMap(h=>h.planets);assert(planets.length>=500);assert.equal(new Set(planets.map(p=>p.pl_name)).size,planets.length);assert(catalog.objects.filter(o=>o.type==='blackhole').length>=2);for(const o of [...nearby.hosts,...catalog.objects]){assert(o.distancePc>0);assert(o.source.startsWith('https://'));assert(M.position(o.raDeg,o.decDeg,o.distancePc));}assert.match(catalog.coordinates.epoch,/not propagated/);assert.match(catalog.milkyWay.note,/illustrative/);});
test('Schwarzschild reference scales with measured mass; absent orbit sizes never become invented positions',()=>{assert(Math.abs(M.schwarzschildKm(1)-2.95333938)<1e-8);assert.equal(M.schwarzschildKm(null),null);const p=M.systemLayout([{pl_orbsmax:null},{pl_orbsmax:.2}]);assert.equal(p[0].radius,null);assert(p[1].radius>0);assert(p.every(x=>x.phaseKnown===false));});
test('Milky Way and galaxy layers are bounded reconstructions with catalog navigation',async()=>{const a=await boot({mobile:true});assert.equal(a.errors.length,0);assert(a.elements.get('loading').hidden);assert.equal(a.renderer.pixelRatio,1.25);assert.equal(a.renderer.options.antialias,false);assert.equal(a.world().children.find(o=>o.isPoints).geometry.attributes.position.count,12000);a.layer('galaxies');assert.equal(a.elements.get('target').children.length,7);a.choose('m31');assert.match(a.facts(),/2,500,000/);assert.match(a.elements.get('object-type').textContent,/CATALOG/);assert(!a.elements.get('observation').hidden);assert.match(a.elements.get('observation-caption').textContent,/NASA, ESA/);});
test('nearby map uses every measured host position and planet diagrams disclose unknown phase and imagery',async()=>{const a=await boot();a.layer('nearby');const points=a.world().children.find(o=>o.isPoints).geometry.attributes.position;assert.equal(points.count,nearby.hosts.length);for(let i=0;i<nearby.hosts.length;i++){const h=nearby.hosts[i],expected=M.position(h.raDeg,h.decDeg,h.distancePc).map(v=>v/3);assert(new THREE.Vector3().fromBufferAttribute(points,i).distanceTo(new THREE.Vector3(...expected))<1e-6);}a.choose('Proxima Cen');assert(!a.elements.get('planet-section').hidden);a.elements.get('actions').children[0].onclick();a.frame(.04);assert.match(a.elements.get('view-note').textContent,/phase, orientation and surface appearance unavailable/);a.elements.get('planet-list').children[0].onclick();assert.match(a.elements.get('object-description').textContent,/illustrative/);assert.match(a.elements.get('object-type').textContent,/CONFIRMED EXOPLANET/);assert.match(a.facts(),/ORBITAL PERIOD/);a.choose(nearby.hosts[1].id);assert.equal(a.world().children.find(o=>o.isPoints).geometry.attributes.position.count,nearby.hosts.length,'selecting another host must restore the coordinate map');});
test('black holes expose real recorded observations, masses and a static default illustration',async()=>{const a=await boot();a.layer('blackholes');assert.match(a.elements.get('observation-caption').textContent,/2017 observations/);assert.match(a.facts(),/4,000,000/);const mat=a.world().children.find(o=>o.material?.isShaderMaterial).material;for(let i=0;i<40;i++)a.frame();assert.equal(mat.uniforms.time.value,0);a.elements.get('actions').children[1].onclick();a.frame(.04);assert(mat.uniforms.time.value>0);a.choose('m87-star');assert.match(a.elements.get('view-title').textContent,/M87/);assert.match(a.facts(),/6,500,000,000/);assert.match(a.elements.get('observation-caption').textContent,/EHT Collaboration/);a.elements.get('fit').onclick();a.frame(.04);assert.match(a.elements.get('object-name').textContent,/M87/,'Fit must not change the selected object');});
test('phone sheets restore focus, hidden tabs stop drawing and a failed catalog never substitutes fake positions',async()=>{const a=await boot({mobile:true});a.elements.get('open-info').focus();a.elements.get('open-info').onclick();assert.equal(a.document.activeElement,a.elements.get('close-info'));a.elements.get('close-info').onclick();assert.equal(a.document.activeElement,a.elements.get('open-info'));assert(a.elements.get('space-info').inert);const count=a.renderer.count;a.document.hidden=true;a.document.dispatch('visibilitychange');for(let i=0;i<30;i++)a.frame();assert.equal(a.renderer.count,count);a.advance(60);a.document.hidden=false;a.document.dispatch('visibilitychange');a.frame();assert.match(a.elements.get('utc-clock').textContent,/12:01/);const bad=await boot({offline:true});assert(!bad.elements.get('loading').hidden);assert.match(bad.elements.get('loading').textContent,/No invented catalog positions/);assert.equal(bad.world().children.length,0);});
test('reduced motion suppresses optional gas illustration; layer changes dispose previous geometry',async()=>{const a=await boot({reduced:true});const old=a.world().children.find(o=>o.isPoints).geometry;let disposed=false;old.addEventListener('dispose',()=>disposed=true);a.layer('blackholes');assert(disposed);const mat=a.world().children.find(o=>o.material?.isShaderMaterial).material;a.elements.get('actions').children[1].onclick();a.frame(.1);assert.equal(mat.uniforms.time.value,0);});

test('mobile draw cap preserves current UTC and object search navigates across catalog scales',async()=>{const a=await boot({mobile:true});const start=a.renderer.count;for(let i=0;i<60;i++)a.frame(1/60);assert.equal(a.renderer.count-start,30);a.elements.get('search').value='TRAPPIST';a.elements.get('search').oninput();assert(a.elements.get('search-results').children.length>0);a.elements.get('search-results').children[0].onclick();a.frame(.04);assert.match(a.elements.get('object-name').textContent,/TRAPPIST/);assert(!a.elements.get('planet-section').hidden);});
test('deep links and failed observation images keep source attribution and usable 3D data',async()=>{const a=await boot({search:'?layer=blackholes'});assert.match(a.elements.get('object-name').textContent,/Sagittarius/);a.elements.get('observation-image').onerror();assert(a.elements.get('observation-image').hidden);assert.match(a.elements.get('observation-caption').textContent,/EHT Collaboration.*Image unavailable/);assert.match(a.elements.get('observation-link').href,/eso.org/);assert(a.world().children.length>0);});
